version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: unless-stopped
    networks:
     - inception
    volumes:
     - db_vol:/var/lib/mysql/
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u ${DB_USER} -p${DB_USER_PWD}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 15s

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
     - 80:80 
     - 443:443
    restart: unless-stopped
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
     - inception
    volumes:
     - wp_vol:/var/www/wordpress
    env_file: .env

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    networks:
     - inception
    volumes:
     - wp_vol:/var/www/wordpress
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "wp core is-installed --path=/var/www/wordpress --allow-root || exit 1"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 15s
  
  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
     - inception
    env_file: .env

  duckdns:
    container_name: duckdns
    build: ./requirements/duckdns/
    depends_on:
      - nginx
    restart: unless-stopped
    networks:
     - inception
    volumes:
     - dns_vol:/duckdns
    env_file: .env

volumes:
   wp_vol:
     driver: local
     driver_opts:
       type: none
       o: bind
       device: BIND_PATH/wordpress
   db_vol:
     driver: local
     driver_opts:
       type: none
       o: bind
       device: BIND_PATH/db
   dns_vol:
     driver: local
     driver_opts:
       type: none
       o: bind
       device: BIND_PATH/duckdns

networks:
  inception: