---
- name: Add a user for ansible tasks
  user:
    name: "{{ user }}"
    shell: "{{ user_shell }}"
    create_home: yes
    state: present
- name: Add ssh key for the user
  authorized_key:
    user: "{{ user }}"
    key: "{{ ssh_public_key }}"
    state: present
- name: Add user to sudoers
  copy:
    src: sudoers_list
    dest: "/etc/sudoers.d/{{ user }}"
    mode: '0440'
- name: Ensure the sudoers file has the correct permission
  file:
    path: "/etc/sudoers.d/{{ user }}"
    owner: root
    group: root
    mode: '0440'