---
- name: Remove docker, if exists
  ansible.builtin.apt:
    name: "{{ docker_uninstall }}"
    state: absent
    purge: yes
- name: Install docker dependencies and update cache
  ansible.builtin.apt:
    name: "{{ docker_dependencies }}"
    state: present
    update_cache: yes
- name: Add GPG key
  ansible.builtin.apt_key:
    url: "{{ docker_gpg_key }}"
    state: present
- name: Add docker repository to apt
  ansible.builtin.apt_repository:
    repo: "{{ docker_repository }}"
    state: present
- name: Install docker
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: latest
    update_cache: yes
- name: Check docker is active
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
- name: Ensure group docker exists
  ansible.builtin.group:
    name: docker
    state: present
- name: Adding ansible user to docker group
  ansible.builtin.user:
    name: "{{ ansible_admin }}"
    groups: docker
    append: yes
- name: Install docker-compose
  ansible.builtin.get_url:
    url: "{{ docker_compose_url }}"
    dest: "{{ docker_compose_dest }}"
    mode: '0755'
- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: "{{ docker_compose_dest }}"
    owner: "{{ ansible_admin }}"
    group: "{{ ansible_admin }}"