---
- hosts: webservers
  become: true

  tasks:
    - name: Create project directory
      file:
        path: /home/ubuntu/app
        state: directory
  
    - name: Copy app resources
      copy:
        src: ../srcs/
        dest: /home/ubuntu/app/

    - name: Start Docker Compose application
      command: docker-compose -f /home/ubuntu/app/docker-compose.yml up -d
      args:
        chdir: /home/ubuntu/app/