---
- hosts: webservers
  become: true

  tasks:
    - name: Create data directories for Docker volumes
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /home/ubuntu/data/wordpress
        - /home/ubuntu/data/db

    - name: Check if Docker volume app_wp_vol exists
      command: docker volume inspect app_wp_vol
      register: wp_vol_check
      ignore_errors: true

    - name: Remove Docker volume app_wp_vol if it exists
      command: docker volume rm app_wp_vol
      when: wp_vol_check.rc == 0

    - name: Check if Docker volume app_db_vol exists
      command: docker volume inspect app_db_vol
      register: db_vol_check
      ignore_errors: true

    - name: Remove Docker volume app_db_vol if it exists
      command: docker volume rm app_db_vol
      when: db_vol_check.rc == 0
    